namespace :db do 
  desc "drops the Ec2TypeSpecification table and rebuilds it"
  task :reset_ec2_type_specifications => :environment do 
    # Most Details: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html
    # EBS Optimization details: http://aws.amazon.com/ec2/instance-types/

    Ec2TypeSpecification.delete_all

    Ec2TypeSpecification.find_or_create_by_api_name("t1.micro",
                                                    name: "Micro",
                                                    api_type: "uODI",
                                                    api_size: "u",
                                                    memory: 613.megabytes,
                                                    compute_units: 2,
                                                    support_32_bit: true,
                                                    support_64_bit: true,
                                                    cores: 2,
                                                    core_type: "virtual burst",
                                                    ephemeral_drives: 0,
                                                    total_ephemeral_storage: 0,
                                                    ebs_optimization: 0,
                                                    io_performance: "low",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 2,
                                                    private_ip_per_eni: 2,
                                                    notes: "cores available for short periods only",
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("m1.small",
                                                    name: "M1 Small",
                                                    api_type: "stdODI",
                                                    api_size: "sm",
                                                    memory: 1.7.gigabytes,
                                                    compute_units: 1,
                                                    support_32_bit: true,
                                                    support_64_bit: true,
                                                    cores: 1,
                                                    core_type: "virtual",
                                                    ephemeral_drives: 1,
                                                    total_ephemeral_storage: 160.gigabytes,
                                                    ebs_optimization: 0,
                                                    io_performance: "moderate",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 2,
                                                    private_ip_per_eni: 4,
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("m1.medium",
                                                    name: "M1 Medium",
                                                    api_type: "stdODI",
                                                    api_size: "med",
                                                    memory: 3.75.gigabytes,
                                                    compute_units: 2,
                                                    support_32_bit: true,
                                                    support_64_bit: true,
                                                    cores: 2,
                                                    core_type: "virtual",
                                                    ephemeral_drives: 1,
                                                    total_ephemeral_storage: 410.gigabytes,
                                                    ebs_optimization: 0,
                                                    io_performance: "moderate",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 2,
                                                    private_ip_per_eni: 6
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("m1.large",
                                                    name: "M1 Large",
                                                    api_type: "stdODI",
                                                    api_size: "lg",
                                                    memory: 7.5.gigabytes,
                                                    compute_units: 4,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 2,
                                                    core_type: "virtual (2 ECU each)",
                                                    ephemeral_drives: 2,
                                                    total_ephemeral_storage: 840.gigabytes,
                                                    ebs_optimization: 500,
                                                    io_performance: "moderate",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 3,
                                                    private_ip_per_eni: 10,
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("m1.xlarge",
                                                    name: "M1 Extra Large",
                                                    api_type: "stdODI",
                                                    api_size: "xl",
                                                    memory: 15.gigabytes,
                                                    compute_units: 8,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 4,
                                                    core_type: "virtual (2 ECU each)",
                                                    ephemeral_drives: 4,
                                                    total_ephemeral_storage: 1680.gigabytes,
                                                    ebs_optimization: 1000,
                                                    io_performance: "high",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 4,
                                                    private_ip_per_eni: 15,
                                                   )


    Ec2TypeSpecification.find_or_create_by_api_name("hs1.8xlarge",
                                                    name: "High Storage 8 XL",
                                                    api_type: "hiStoreODI",
                                                    api_size: "xxxxxxxxl",
                                                    memory: 117.gigabytes,
                                                    compute_units: 35,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 16,
                                                    core_type: "cores + hyperthreads",
                                                    ephemeral_drives: 24,
                                                    total_ephemeral_storage: 48.terabytes,
                                                    ebs_optimization: 0,
                                                    io_performance: "very high",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 8,
                                                    private_ip_per_eni: 30,
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("cr1.8xlarge",
                                                    name: "High-Memory Cluster 8 XL",
                                                    api_type: "clusterHiMemODI",
                                                    api_size: "xxxxxxxxl",
                                                    memory: 244.gigabytes,
                                                    compute_units: 88,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 16,
                                                    core_type: "Intel Xeon E5-2670, eight-core",
                                                    ephemeral_drives: 2,
                                                    total_ephemeral_storage: 240.gigabytes,
                                                    ebs_optimization: 0,
                                                    io_performance: "very high",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 8,
                                                    private_ip_per_eni: 30,
                                                   )


    Ec2TypeSpecification.find_or_create_by_api_name("m2.4xlarge",
                                                    name: "High-Memory 4 XL",
                                                    api_type: "hiMemODI",
                                                    api_size: "xxxxl",
                                                    memory: 68.4.gigabytes,
                                                    compute_units: 26,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 8,
                                                    core_type: "virtual (3.25 ECU each)",
                                                    ephemeral_drives: 2,
                                                    total_ephemeral_storage: 1680.gigabytes,
                                                    ebs_optimization: 1000,
                                                    io_performance: "high",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 8,
                                                    private_ip_per_eni: 30,
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("m2.xlarge",
                                                    name: "High-Memory XL",
                                                    api_type: "hiMemODI",
                                                    api_size: "xl",
                                                    memory: 17.1.gigabytes,
                                                    compute_units: 6.5,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 2,
                                                    core_type: "virtual (3.25 ECU each)",
                                                    ephemeral_drives: 1,
                                                    total_ephemeral_storage: 410.gigabytes,
                                                    ebs_optimization: 0,
                                                    io_performance: "moderate",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 4,
                                                    private_ip_per_eni: 15,
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("m2.2xlarge",
                                                    name: "High-Memory 2 XL",
                                                    api_type: "hiMemODI",
                                                    api_size: "xxl",
                                                    memory: 34.2.gigabytes,
                                                    compute_units: 13,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 4,
                                                    core_type: "virtual (3.25 ECU each)",
                                                    ephemeral_drives: 1,
                                                    total_ephemeral_storage: 840.gigabytes,
                                                    ebs_optimization: 500,
                                                    io_performance: "high",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 4,
                                                    private_ip_per_eni: 30,
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("hi1.4xlarge",
                                                    name: "High I/O 4 XL",
                                                    api_type: "hiIoODI",
                                                    api_size: "xxxxl",
                                                    memory: 60.5.gigabytes,
                                                    compute_units: 35,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 8,
                                                    core_type: "virtual (4.37 ECU each)",
                                                    ephemeral_drives: 2,
                                                    total_ephemeral_storage: 2.terabytes,
                                                    ebs_optimization: 0,
                                                    io_performance: "very high",
                                                    spot_available: false,
                                                    elastic_network_interfaces: 8,
                                                    private_ip_per_eni: 30,
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("hs1.8xlarge",
                                                    name: "High Storage 8 XL",
                                                    api_type: "hiStoreODI",
                                                    api_size: "xxxxxxxxl",
                                                    memory: 117.gigabytes,
                                                    compute_units: 35,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 16,
                                                    core_type: "cores + hyperthreads",
                                                    ephemeral_drives: 24,
                                                    total_ephemeral_storage: 48.terabytes,
                                                    ebs_optimization: 0,
                                                    io_performance: "very high",
                                                    spot_available: false,
                                                    elastic_network_interfaces: 8,
                                                    private_ip_per_eni: 30,
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("c1.medium",
                                                    name: "High-CPU Medium",
                                                    api_type: "hiCPUODI",
                                                    api_size: "med",
                                                    memory: 1.7.gigabytes,
                                                    compute_units: 5,
                                                    support_32_bit: true,
                                                    support_64_bit: true,
                                                    cores: 2,
                                                    core_type: "virtual (2.5 ECU each)",
                                                    ephemeral_drives: 1,
                                                    total_ephemeral_storage: 340.gigabytes,
                                                    ebs_optimization: 0,
                                                    io_performance: "moderate",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 2,
                                                    private_ip_per_eni: 6,
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("c1.xlarge",
                                                    name: "High-CPU XL",
                                                    api_type: "hiCPUODI",
                                                    api_size: "xl",
                                                    memory: 7.gigabytes,
                                                    compute_units: 20,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 8,
                                                    core_type: "virtual (2.5 ECU each)",
                                                    ephemeral_drives: 4,
                                                    total_ephemeral_storage: 420.gigabytes,
                                                    ebs_optimization: 1000,
                                                    io_performance: "high",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 4,
                                                    private_ip_per_eni: 15,
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("cg1.4xlarge",
                                                    name: "Cluster GPU 4 XL",
                                                    api_type: "clusterGPUI",
                                                    api_size: "xxxxl",
                                                    memory: 22.5.gigabytes,
                                                    compute_units: 33.5,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 8,
                                                    core_type: "Intel Xeon X5570, quad-core with hyperthread",
                                                    ephemeral_drives: 2,
                                                    total_ephemeral_storage: 1680.gigabytes,
                                                    ebs_optimization: 0,
                                                    io_performance: "very high",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 8,
                                                    private_ip_per_eni: 30,
                                                    notes: "plus 2 NVIDIA Tesla M2050 GPUs")

    Ec2TypeSpecification.find_or_create_by_api_name("cc1.4xlarge",
                                                    name: "Cluster Compute 4 XL",
                                                    api_type: "clusterComputeI",
                                                    api_size: "xxxxl",
                                                    memory: 22.5.gigabytes,
                                                    compute_units: 33.5,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 8,
                                                    core_type: "Intel Xeon X5570, quad-core with hyperthread",
                                                    ephemeral_drives: 2,
                                                    total_ephemeral_storage: 1690.gigabytes,
                                                    ebs_optimization: 0,
                                                    io_performance: "very high",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 0,
                                                    private_ip_per_eni: 0,
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("cc2.8xlarge",
                                                    name: "Cluster Compute 8 XL",
                                                    api_type: "clusterComputeI",
                                                    api_size: "xxxxxxxxl",
                                                    memory: 60.5.gigabytes,
                                                    compute_units: 88,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 16,
                                                    core_type: "Intel Xeon E5-2670, eight-core with hyperthread",
                                                    ephemeral_drives: 4,
                                                    total_ephemeral_storage: 3360.gigabytes,
                                                    ebs_optimization: 0,
                                                    io_performance: "very high",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 8,
                                                    private_ip_per_eni: 30,
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("m3.2xlarge",
                                                    name: "M3 Double XL",
                                                    api_type: "secgenstdODI",
                                                    api_size: "xxl",
                                                    memory: 30.gigabytes,
                                                    compute_units: 26,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 8,
                                                    core_type: "virtual (3.25 ECU each)",
                                                    ephemeral_drives: 0,
                                                    total_ephemeral_storage: 0,
                                                    ebs_optimization: 1000,
                                                    io_performance: "high",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 4,
                                                    private_ip_per_eni: 30,
                                                   )

    Ec2TypeSpecification.find_or_create_by_api_name("m3.xlarge",
                                                    name: "M3 XL",
                                                    api_type: "secgenstdODI",
                                                    api_size: "xl",
                                                    memory: 15.gigabytes,
                                                    compute_units: 13,
                                                    support_32_bit: false,
                                                    support_64_bit: true,
                                                    cores: 4,
                                                    core_type: "virtual (3.25 ECU each)",
                                                    ephemeral_drives: 0,
                                                    total_ephemeral_storage: 0,
                                                    ebs_optimization: 500,
                                                    io_performance: "moderate",
                                                    spot_available: true,
                                                    elastic_network_interfaces: 4,
                                                    private_ip_per_eni: 15,
                                                   )

  end 
end 
